name: "Setup Environment"
runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - run: yarn --immutable
      shell: bash
    - run: yarn prebuild
      shell: bash
    # - name: Archive artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: generated
    #     path: "**/generated"
    #     if-no-files-found: error