#:schema node_modules/wrangler/config-schema.json
name = "pikku-workspace-starter"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[vars]
NODE_ENV = "production"

[triggers]
crons = ["* * * * 1"]
