name: 'Restore Environment'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - run: yarn --immutable
      shell: bash
    - name: Download generated artifacts
      uses: actions/download-artifact@v4
      with:
        name: generated
