name: Master
run-name: The master and release workflow
on: [push]
env:
  POSTGRES_CREDENTIALS: '{"host":"localhost","port":5432,"user":"postgres","password":"password","database":"vramework-workspace-starter"}'
jobs:
  setup:
    name: Setup and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: vramework-workspace-starter
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - run: yarn test

  express:
    name: Express Docker
    uses: ./.github/workflows/backend-docker-build-and-publish.yml
    needs: setup
    with:
      dockerfile-path: 'docker/Dockerfile.express'
      image-name: 'workspace-starter-express'
      image-tag: 'latest'

  fastify:
    name: Fastify Docker
    uses: ./.github/workflows/backend-docker-build-and-publish.yml
    needs: setup
    with:
      dockerfile-path: 'docker/Dockerfile.fastify'
      image-name: 'workspace-starter-fastify'
      image-tag: 'latest'

  uws:
    name: UWS Docker
    uses: ./.github/workflows/backend-docker-build-and-publish.yml
    needs: setup
    with:
      dockerfile-path: 'docker/Dockerfile.uws'
      image-name: 'workspace-starter-uws'
      image-tag: 'latest'

  ws:
    name: WS Docker
    uses: ./.github/workflows/backend-docker-build-and-publish.yml
    needs: setup
    with:
      dockerfile-path: 'docker/Dockerfile.ws'
      image-name: 'workspace-starter-ws'
      image-tag: 'latest'

  next-app:
    name: Next App
    needs: setup
    uses: ./.github/workflows/next-docker-build-and-publish.yml
    with:
      app-path: 'apps/next-app'
      dockerfile-path: 'docker/Dockerfile.nextjs-app'
      image-name: 'workspace-starter-nextjs-app'
      image-tag: 'latest'
